public enum Layers {
	DEFAULT = 0,
	TRANSPARENTFX = 1,
	IGNORERAYCAST = 2,
	BUILTIN_EMPTY = 3,
	WATER = 4,
	BUILTIN_EMPTY2 = 5,
	BUILTIN_EMPTY3 = 6,
	BUILTIN_EMPTY4 = 7,
	SELECTABLE = 8,
	FLOOR = 9
};

public enum LayersMask {
	DEFAULT = 1 << 0,
	TRANSPARENTFX = 1 << 1,
	IGNORERAYCAST = 1 << 2,
	BUILTIN_EMPTY = 1 << 3,
	WATER = 1 << 4,
	BUILTIN_EMPTY2 = 1 << 5,
	BUILTIN_EMPTY3 = 1 << 6,
	BUILTIN_EMPTY4 = 1 << 7,
	SELECTABLE = 1 << 8,
	FLOOR = 1 << 9
};
