public enum Layers {
	DEFAULT = 0,
	TRANSPARENTFX = 1 << 0,
	IGNORERAYCAST = 1 << 1,
	BUILTIN_EMPTY = 1 << 2,
	WATER = 1 << 3,
	BUILTIN_EMPTY2 = 1 << 4,
	BUILTIN_EMPTY3 = 1 << 5,
	BUILTIN_EMPTY4 = 1 << 6,
	SELECTABLE = 1 << 7,
	FLOOR = 1 << 8
};
